### ISSUE TITLE
superceded by what?

### ISSUE THREAD

**Issue by bbigras** [rogpeppe/go-charset#3]
This repo's description says "superceded" but doesn't specific which package supercede it.

EDIT: maybe see https://groups.google.com/d/msg/Golang-nuts/FHmzYmM5r5Y/0LMjMDlZCwAJ

**Comment by rogpeppe** [comment]
Yes, it's superseded by the packages in golang.org/x/text, which were partially influenced by the design of go-charset. I'm a little surprised it still works :)
